### ISSUE TITLE
Package announcement?

### ISSUE THREAD

**Issue by azev77** [lalvim/PartialLeastSquaresRegressor.jl#15]
Hi @lalvim 
I'm excited about your updated package! 
Have you considered making an announcement here: https://discourse.julialang.org/c/community/packages/47
It can get your package some attention.

**Comment by lalvim** [comment]
Ok, nice.  
I prepared a text here, looking for a pattern there. Can I advertise?

Another point.
Is MLJ interested in having https://github.com/lalvim/Perceptrons.jl in the registry?
It is a package with different perceptron implementations that I do not seem to have in mlj or scikit.

**Comment by azev77** [comment]
1. For a sample announcement you can check out [this link](https://discourse.julialang.org/t/linregoutliers-a-julia-package-for-detecting-outliers-in-linear-regression/47280). 
2. I don't know about Perceptrons.jl, I don't use that much. Ask @ablaom @tlienart ...

**Comment by lalvim** [comment]
Thanks @azev77 . Done!

**Comment by lalvim** [comment]
I couldn't reference you there @azev77 . 

This is the announcement.
https://discourse.julialang.org/t/ann-partialleastsquaresregressor-jl/48549

**Comment by ablaom** [comment]
> Another point.
Is MLJ interested in having https://github.com/lalvim/Perceptrons.jl in the registry?
It is a package with different perceptron implementations that I do not seem to have in mlj or scikit.

Happy to guide implementation of the MLJ model interface for Perceptrons.jl. The docs for new implementations are [here](https://alan-turing-institute.github.io/MLJ.jl/dev/quick_start_guide_to_adding_models/). These models would receive features as a Tables.jl-compatible table (could be a wrapped matrix) which you materialise as a matrix for your models. However, feature-sparse data is not supported yet.

**Comment by lalvim** [comment]
Nice @ablaom I will work on that and call you there on a new issue of perceptrons package.
