### ISSUE TITLE
Extract Loading and Score plot

### ISSUE THREAD

**Issue by sawenchalmers** [lalvim/PartialLeastSquaresRegressor.jl#26]
How can loadings and scores be extracted after performing fit using `fit!(pls_machine, rows = train)`?

**Comment by ablaom** [comment]
@lalvim Should probably answer this. But, more generally, if you are seeking access to learned parameters in an MLJ machine, use `fitted_params(mach)`, if it is some other byproduct of training, use `report(mach)`. Have you tried these?

**Comment by sawenchalmers** [comment]
Perfect, this is what I needed.
